# Generated by Django 4.1.7 on 2023-03-31 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='страна')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='город')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='улица')),
                ('house', models.PositiveIntegerField(blank=True, null=True, verbose_name='номер дома')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название продукта')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='модель')),
                ('date', models.DateField(verbose_name='Дата выхода')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('FACTORY', 'Завод'), ('RETAIL', 'Розничная сеть'), ('ENTREPRENEUR', 'Индивидуальный предприниматель')], max_length=50)),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('debt', models.FloatField(blank=True, null=True, verbose_name='задолженность')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mvideo.supplier', verbose_name='поставщик')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mvideo.contact', verbose_name='контакты')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mvideo.product', verbose_name='продукты')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
    ]
